language: php
php: '7.0'
before_install:
- phpenv config-rm xdebug.ini
- composer config --global github-oauth.github.com $GITHUB_TOKEN
install: composer install --no-interaction
script: make ci
after_script: bash <(curl -s https://codecov.io/bash)
env:
  global:
    secure: s/2dc/c+bfttna6csRdXKOcVn3vsso1i4IBpz9okWlS7d1Pq39VgCVmWWcZxCslEbsWbKjlsx8Ogd8biRdXWoMShXYsyoL/U9/0Iw0NL7sSIhXU2vhDbq+hyGwy8scRgOrj0WWGu4IhOsFDzM/EULMGUTMKMQjIs4DPPTKHUl0d4ipFiJ/kosT6n/JbdE0WznRJGcrIwStqaVs4LvK/CV7OHxY2G/1U3HsL21niOEGDUyXoQ5lLqbmPzqMJGkSeG2aAlQND5eIbLzkfN8YyERxx5qzp42aU8ohFQq06eAXVHAmyNFq4SOgBciNWqHcNjZJQJiOpZz7A1FCRZAA2p74aGutFG5LY1ZSPGzRU527FcT8KEnvww3lfUz2O4LOSHMSkV3c803GH35qUMOyJjj3wrvarZ74j6Va1qlyk+TE7M4IY3ZfPwO0gggOTBl5GYOwTyfBXvZ+g/pgydBWZeKdUaRtDCRlKEtOHmL7lP9CJb+Ju3ZefJBoJx4dQzqM3GDVmnSgbUJK/LE2ww9uhTzo9MdIcw2Z5HGh80p3/jPfMHjZhpDMGw8gdpkvLRFx5PaieCai6cS0jRz4hdzPh/dpECCjKGeP9x2OggpWuV6I9kiKjmDzY3Eg71dd7J5xsaHAK9RIyG6A1kF4gtEpd3JDZJn3yUS7SMS4S04r3HqJw=
cache:
  directories:
  - $HOME/.composer
